{{- if .Values.serviceAccount.gateway.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.gateway.name }}
  annotations:
{{- range $key, $value := .Values.serviceAccount.gateway.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
